identifier: lcq8y471d8na2ff5
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: /home/rafal/IdeaProjects/my-blog/my-blog
distFolder: dist/my-blog
outDir: /home/rafal/IdeaProjects/my-blog/my-blog/dist/static
handle404: ''
allowErrorCollect: false
